= workspace
:toc: left
:sectnums:

Vagrantでいつでも捨てて再構築できる開発環境を構築する。
Infrastructure as Codeするなら自分用の開発環境だってコード化したい。
やらかしたって `vagrant destroy && vagrant up` でまたやり直せる。
もう `rm -rf` だって怖くない。
（マウントしてるホストのファイルは死ぬ）

== 検証環境

* Ubuntu 19.04
* Windows 10 home

== Vagrantを使えるようにする手順

* https://www.virtualbox.org/wiki/Linux_Downloads[VirtualBox]のインストール
** 6.1.6をインストールした
* https://www.vagrantup.com/[Vagrant]のインストール
** 2.2.7をインストールした

== 使い方

以下のコマンドを入力する。

[source,bash]
----
cd ubuntu
vagrant init
vagrant up
vagrant ssh
----

== ディレクトリ

各ディレクトリの役割は以下の通り。

[options="header"]
|=================
| ディレクトリ | 説明
| common | ubuntu/ubuntu-guiから参照されるプロビジョニングスクリプト
| ubuntu-gui | Ubuntu環境でGUIを使う
| ubuntu | Ubuntu環境でCUIのみ
| main | 普段使いのUbuntu環境。自作のBox環境を使用する
|=================

mainのvm.boxに指定している `jiro4989/ubuntu` はネット上には存在しない。
上記Boxは、 このリポジトリのubuntuディレクトリ配下で `vagrant up` してプロビジョニングしたVMを出力したものである。

普段づかいの仮想環境を再構築するときに
毎回プロビジョニングしなおすのは時間がかかる。

プロビジョニング済みのBoxをローカルに保存しておき
mainからはプロビジョニング済みのBoxを使い回すことで、
プロビジョニングにかかる時間を短縮する。
(仮想環境のゴールデンイメージ化)

`jiro4989/ubuntu` Boxを作成するための手順は以下。

[source,bash]
----
cd ubuntu
vagrant up
vagrant package
vagrant box add jiro4989/ubuntu package.box
vagrant box list
----
