= workspace
:toc: left
:sectnums:

いつでも捨てて再構築できる開発環境を構築する。

== 前提条件

* Windows 11 Home
* Ubuntu 26.04 on WSL2
** https://scrapbox.io/jiro4989/WSL2%E3%81%AE%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB[WSL2のインストール]を参考にWSL2環境を構築する

== WSL2 Ubuntu 環境の構築

新規に Ubuntu 環境を構築する場合は、以下のコマンドを実行する。

[source,powershell]
----
# インストール可能なリストを確認
wsl --list --online

# インストール
wsl --install -d Ubuntu-26.04
----

Windows Terminal の場合、新しくディストリビューションを追加すると
勝手にプロファイルに追加してくれる。一度 Windows Terminal を終了して
再度起動し直すと、おそらくプロファイルが追加されているはず。
以降は、このプロファイルから Ubuntu 環境にアクセスする。

== 使い方

Ubuntu 26.04 環境を WSL2 で立ち上げたら、以下の手順に従って環境を構築する。

* https://github.com/jiro4989/workspace/tree/master/wsl2_nix[wsl2_nix/README.adoc]

== ディレクトリ

=== windows

Windowsホストに必要なツール郡をインストールする。
また、WSL2周りの運用に使うスクリプトを管理する。

=== wsl2_nix

Nix パッケージマネージャを中心に置いた WSL2 環境。
2026/05/28 現在のメインな環境。

昨今のサプライチェーン攻撃リスクを鑑みると、
都度シェルスクリプトでツールをインストールしたり、
厳密なバージョン管理をしない開発環境の構築はリスクが高い。

そこで、厳密なバージョン固定が可能な Nix を試験的に採用しつつ、
諸々使っていたツールなどを一新して開発環境を再構築したもの。

Nix 公式パッケージが思っていた以上にいろんなツールを登録してくれているおかげで、
旧 wsl2 環境構築よりも簡単に諸々ツールをインストールできるようになった。
また、Nix に移行したことで、ツールのインストールは Nix、
環境構築は go-task と役割の線引きをするようになり、保守性も高まった。

=== wsl2 (DEPRECATED)

旧開発環境。現在は使っていない。

Windows 11のWSL2上で実行するスクリプトを管理する。
Nix 環境に移行してからは使っていない。

シェルスクリプトで開発環境をセットアップするオーソドックスな手法を取っている。
setup.sh を見ればわかるが、泥臭いコードを書いているし、
厳密なバージョン管理をしてなくて、今見ると結構良くない実装になっている。

=== docker (DEPRECATED)

開発環境をすべてdocker上に閉じ込めたもの。

環境の使い方は https://github.com/jiro4989/workspace/tree/master/docker[docker/README.adoc] を参照。
2025/01/09 現在はほぼ使っていないが、docker が使いたくなった場合のために一応残している。

=== vagrant (DEPRECATED)

以前はvagrantを使っていたけれど、こっちはもう使っていない。

一応当時の環境構築手順とかは残してある。
詳細は https://github.com/jiro4989/workspace/tree/master/vagrant[vagrant/README.adoc] を参照。

== 関連

* https://github.com/jiro4989/dotfiles
