= workspace
:toc: left
:sectnums:

Vagrantでいつでも捨てて再構築できる開発環境を構築する。
Infrastructure as Codeするなら自分用の開発環境だってコード化したい。
やらかしたって `vagrant destroy && vagrant up` でまたやり直せる。
もう `rm -rf` だって怖くない。
（マウントしてるホストのファイルは死ぬ）

== 検証環境

* Ubuntu 19.04
* Windows 10 home

== Vagrantを使えるようにする手順

* https://www.virtualbox.org/wiki/Linux_Downloads[VirtualBox]のインストール
** 6.1.6をインストールした
* https://www.vagrantup.com/[Vagrant]のインストール
** 2.2.7をインストールした

== 使い方

以下のコマンドを入力する。

[source,bash]
----
./setup.sh

cd main
vagrant up
vagrant ssh
----

=== 単体のVMを作り直す

以下のコマンドを入力する。

[source,bash]
----
./build_box.sh base
----

=== 構築済みVMのスナップショットを取る

以下のコマンドを入力する。

[source,bash]
----
./save_snapshot.sh base
----

== ディレクトリ

各ディレクトリの役割は以下の通り。

[options="header"]
|=================
| ディレクトリ | 説明
| base | すべての環境に共通で必要となる環境
| base-gui | base boxを使用し、GUI関連の環境を追加した環境
| main | [deprecated] base boxを使用した環境
| main-gui | [deprecated] base-gui boxを使用した環境
|=================

base環境を `vagrant up` し、その環境のboxを各種環境から参照する。
各環境の依存関係は以下の通り。

 base -+- base-gui --- main-gui
       `- main

普段使う環境は `main` と `main-gui` で、 `base` と `base-gui` は直接使用しない。
`base` と `base-gui` で作成した環境をローカルにboxとして保存し、
`main` と `main-gui` はローカルのboxを使用して環境を起動する。

プロビジョニング済みのboxをローカルに保存し、
`main` からはプロビジョニング済みのboxを使い回すことで、
環境再構築にかかる時間を短縮する。
(仮想環境のゴールデンイメージ化)
