= docker
:toc: left
:sectnums:

Docker上に構築した開発環境。

== コンテナ構成

Dockerfileはマルチステージ構成にしている。
ステージは2階層に分けており、それぞれ base ステージと言語ランタイムステージが存在する。
各言語ランタイムはいずれも base ステージを継承している。

* 共通ステージ
** base
* 言語ランタイムステージ
** go
** nim
** java
** node
** infra

すべてのステージで共通で必要なリソースは base ステージに定義している。

ランタイムステージ固有で必要なパッケージは各ランタイムのステージに定義する。
例えば、xrdpパッケージ等はGUIアプリの開発目的でしか使わず、現状GUIアプリはJavaで
しか作っていないため、 java ステージにのみ定義している。

== 使い方

=== 事前準備

==== 環境変数の設定

コンテナ内に作成するユーザ用にパスワードを .envrc に設定する。
環境変数を読み込むのには https://github.com/direnv/direnv[direnv] を使用する。

以下のコマンドを実行し、環境変数の値を任意の値に書き換える。

[source,bash]
----
cp .envrc.sample .envrc
vim .envrc
direnv allow
----

==== .netrc の準備

コンテナ上でGitHubにPushとかできるようにするために .netrc ファイルにGitHubの
PersonalAccessTokenを設定する。

以下のパスにファイルを作成すること。

* `~/.netrc`

=== ヘルプ出力

[source,bash]
----
make
----

=== ビルド

単純にビルドする場合は以下のコマンドを実行する。

[source,bash]
----
make build
----

キャッシュを無視して強制的にビルドを実行する。
`docker build --no-cache` を同じ。

[source,bash]
----
make build NO_CACHE=true
----

=== 環境の立ち上げ

環境を立ち上げる。Dockerイメージがまだビルドされていなかったらビルドする。
停止中のコンテナが存在する場合はコンテナを再開する。

[source,bash]
----
make start TARGET=go
----

=== 環境の停止

コンテナを止める。 `TARGET` を指定しない場合はすべてのコンテナを止める。

[source,bash]
----
make stop
----

=== 環境の削除

コンテナを削除する。 `TARGET` を指定しない場合はすべてのコンテナを削除する。

[source,bash]
----
make clean
----

== GUI アプリの開発

基本的に GUI アプリは全部 Java で作る。

=== リモートデスクトップでJava環境につなぐ

Javaのコンテナに入って以下のコマンドを実行する。

[source,bash]
----
# パスワードを変更。
# デフォルトではパスワード未設定なので
# リモートデスクトップ接続時の認証情報とどうやっても一致しない。
sudo passwd jiro4989

sudo /etc/init.d/xrdp start
----

次に Windows ホスト側で「リモートデスクトップ接続」を起動する。
接続先は `localhost:3350` で、パスワードは `passwd` で設定した値。

これでOK。

=== ターミナルの起動

リモートデスクトップ接続先のデフォルトブラウザを使おうとしてもエラーになる。
`xterm` を指定して起動すると接続できる。

`xterm` がインストールされていなければ、以下のコマンドでインストールする。

[source,bash]
----
sudo apt update -yqq
sudo apt install -yqq xterm
----

=== VSCodeでコンテナにつなぐ

WSL2 上の docker 環境を使っているので、VSCode でリモートコンテナする場合は一工夫必要。
まず VSCode で Remote WSL でつなぐ。
Remote WSL で繋いでから Remote Container でつなぐ。
以上。
