# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"

  config.vm.network "forwarded_port", guest: 80, host: 10080
  config.vm.network "forwarded_port", guest: 3000, host: 13000
  config.vm.synced_folder "C:\\Users\\jiro4989\\.ssh", "/home/vagrant/.host.ssh"
  config.vm.synced_folder "C:\\Users\\jiro4989\\shared", "/home/vagrant/shared"
  config.vm.provision "file", source: "~/.netrc", destination: ".netrc"

  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    # vb.memory = "1024"
    vb.customize [
      "modifyvm", :id,
      "--cableconnected1", "on",
      "--clipboard", "bidirectional", # クリップボードの共有
    ]
  end

  config.vm.provision "shell", path: "init.sh"
end
