= WSL2 Nix
:toc: left
:sectnums:

WSL2 上の Ubuntu 環境を Nix で構築する。

== 手順

=== Nix のインストール

https://nixos.org/download/#nix-install-windows[公式の手順]にしたがって、
インストールスクリプトを実行する。
何回か入力を求められる。

[source,shell]
----
sh <(curl --proto '=https' --tlsv1.2 -L https://nixos.org/nix/install) --daemon
----

シェルを再起動しないと Nix が有効にならないため、スクリプトが正常終了したら
一度 Ubuntu から抜けて入りなおすこと。

入り直したら Flakes と Nix command を有効化するために設定ファイルを編集する。

[source,shell]
----
$ mkdir -p ~/.config/nix
$ vi ~/.config/nix/nix.conf
# または
$ sudo vi /etc/nix/nix.conf
----

上記ファイルに、以下の記述を追加する。

[source,nix]
----
experimental-features = nix-command flakes
----

=== flake による環境構築

[source,shell]
----
cd ~
mkdir -p workspace
cd workspace
git clone https://github.com/jiro4989/workspace
cd workspace/wsl2_nix

nix develop

task setup
----

=== Neovim プラグインのインストール

以下のコマンドで neovim を起動する。

[source,shell]
----
nvim
----

neovim 上で以下のコマンドを実行して、プラグインをインストールする。

[source,shell]
----
:PlugInstall
----

以降は `nix develop` で開発用のシェルに切り替えて作業する。

=== Doom Emacs のセットアップ

Emacs 用の設定フレームワークの Doom をセットアップする。
以下のコマンドを実行する。

[source,shell]
----
git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.config/emacs
~/.config/emacs/bin/doom install
----

環境によっては `$HOME/.emacs.d` ディレクトリが存在していると doom の設定ファイルが読みこまれないことがある。
その場合は、`$HOME/.emacs.d` ディレクトリを削除すれば、doom が読みこまれるようになる。

Doom 用の設定ファイルは `$HOME/.config/doom` 配下に配置されるのだが、
前述の `task setup` で自分用の設定がシンボリックリンクされる。

`doom install` を実行する前にシンボリックリンクしているため、もしかしたら install で設定ファイルが上書きされるかもしれない。
そのときは一度 `$HOME/.config/doom` を削除してから install しなおすか、`task setup` しなおすこと。

`$HOME/.config/doom` のファイルを変更したら、
そのたび `doom sync` して emacs を再起動しないといけない点に注意。

==== SKK による日本語入力

なぜか WSL2 上で Emacs を起動すると日本語 IME が反応しなかったため、
しかたなく WSL2 上では Emacs 上の SKK で日本語入力する。
SKK による最低限の日本語入力に必要なショートカットキー操作は以下のとおり。

* C-x C-j: 英語 ←→ かなモードの切り替え
* q: かなモード中に入力すると、カタカナ入力に変わる
* /: かなモード中に入力すると、一時的に英語入力ができる

== 参考

. https://zenn.dev/asa1984/books/nix-hands-on[Nix入門: ハンズオン編]
