---
version: '3'

tasks:
  setup:
    desc: '環境をセットアップする'
    cmds:
      - task: setup:dotfiles
      - task: setup:fisher
      - task: setup:emacs
      - task: setup:apt

  setup:dotfiles:
    desc: 'dotfiles をセットアップする'
    cmds:
      - task: setup:dotfiles_repo
      - task: setup:dotfiles_config

  setup:dotfiles_repo:
    desc: 'dotfiles リポジトリを clone する'
    dir: ../..
    cmds:
      - git clone https://github.com/jiro4989/dotfiles
    status:
      - test -d dotfiles

  setup:dotfiles_config:
    desc: 'dotfiles の設定をリンクする'
    deps: [setup:dotfiles_repo]
    dir: ../../dotfiles
    cmds:
      - ./setup.sh

  setup:fisher:
    desc: 'fisher をセットアップする'
    cmds:
      - fish setup_fisher.fish

  setup:emacs:
    desc: 'Doom Emacs をセットアップする'
    cmds:
      - task: setup:emacs_repo
      - task: setup:emacs_config

  setup:emacs_repo:
    desc: 'Doom Emacs リポジトリを clone する'
    cmds:
      - git clone --depth 1 https://github.com/doomemacs/doomemacs $HOME/.config/emacs
    status:
      - test -d $HOME/.config/emacs

  setup:emacs_config:
    desc: 'Doom Emacs の設定をする'
    deps: [setup:emacs_repo]
    cmds:
      - ~/.config/emacs/bin/doom install

  setup:apt:
    desc: 'apt package をインストールする'
    cmds:
      - task: setup:apt:update
      - task: setup:apt:font

  setup:apt:update:
    desc: 'apt update する'
    cmds:
      - sudo apt update -yqq
      - sudo apt upgrade -yqq

  setup:apt:font:
    desc: 'font をインストールする'
    cmds:
      - sudo apt install -y fonts-noto-cjk
