---
version: '3'

tasks:
  setup:
    desc: '環境をセットアップする'
    cmds:
      - task: setup:dotfiles
      - task: setup:fisher

  setup:dotfiles:
    desc: 'dotfiles をセットアップする'
    cmds:
      - task: setup:dotfiles_repo
      - task: setup:dotfiles_config

  setup:dotfiles_repo:
    desc: 'dotfiles リポジトリを clone する'
    dir: ../..
    cmds:
      - git clone https://github.com/jiro4989/dotfiles
    status:
      - test -d dotfiles

  setup:dotfiles_config:
    desc: 'dotfiles の設定をリンクする'
    deps: [setup:dotfiles_repo]
    dir: ../../dotfiles
    cmds:
      - ./setup.sh

  setup:fisher:
    desc: 'fisher をセットアップする'
    cmds:
      - fish setup_fisher.fish
