---
version: '3'

tasks:
  setup:
    desc: '環境をセットアップする'
    cmds:
      - task: setup:git_config

  setup:git_config:
    desc: 'git config を設定する'
    cmds:
      - git config --global user.email "jiroron666@gmail.com"
      - git config --global user.name "jiro4989"
    status:
      - git config user.email
      - git config user.name
