# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "jiro4989/ubuntu-20.04-20201212"

  config.vm.network "forwarded_port", guest: 80, host: 80
  config.vm.network "forwarded_port", guest: 3000, host: 3000
  config.vm.network "forwarded_port", guest: 5000, host: 5000
  config.vm.network "forwarded_port", guest: 5001, host: 5001
  config.vm.network "forwarded_port", guest: 5002, host: 5002
  config.vm.network "forwarded_port", guest: 9630, host: 9630

  config.vm.synced_folder "C:\\Users\\jiro4989\\.ssh", "/home/vagrant/.host.ssh"
  config.vm.synced_folder "C:\\Users\\jiro4989\\shared", "/home/vagrant/shared"
  config.vm.provision "file", source: "~/.netrc", destination: ".netrc"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "8192" # RAMを使える量を変更
    vb.cpus = 4
    vb.customize [
      "modifyvm", :id,
      "--cableconnected1", "on",
      "--vram", "256", # ビデオメモリ確保（フルスクリーンモードにするため
      "--clipboard", "bidirectional", # クリップボードの共有
      "--accelerate3d", "on",
      "--hwvirtex", "on",
      "--nestedpaging", "on",
      "--largepages", "on",
      "--ioapic", "on",
      "--pae", "on",
      "--paravirtprovider", "legacy",
    ]
    # NOTE: focal64 box bug: https://discuss.hashicorp.com/t/ubuntu-focal64-box-not-starting/14119
    vb.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
    vb.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL]
  end

  config.vm.provision "shell", path: "init.sh"
end
